import luna
#group = luna.Group(create = True, name = 'compute1', osimage = 'compute1', bmcsetup = 'base', bmcnetwork = 'internal')
#group = luna.Group(create = True, name = 'compute2', osimage = 'compute1', bmcsetup = 'base', bmcnetwork = 'internal', interfaces = ['eth0'])
group = luna.Group('compute2')
group.add_interface('eht1')
group.set_net_to_if('eht1', 'internal')
group.del_net_from_if('eht1')
group.del_interface('eht1')
group.set_if_parms('eth0', 'BOOTPROTO=none\nONBOOT=yes')
print group.get_if_parms('eth0')
