import luna
opt = luna.Options(create = True)
ifcfg = luna.IfCfg(name = 'internal', create=True, NETWORK = '192.168.17.10', PREFIX = 23, NETMASK = '255.255.255.0' )
print ifcfg.reserve_ip()
print ifcfg.reserve_ip()
print ifcfg.reserve_ip(100)
print ifcfg.reserve_ip(20)
print ifcfg.reserve_ip(21)
print ifcfg.reserve_ip(22)
#print ifcfg.reserve_ip(4)
#print ifcfg.reserve_ip(300)
#print ifcfg.set('PREFIX', 24)
#ifcfg.delete()
#opt.delete()
